<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>android-icon-48x48.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="android-icon-48x48.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Emgu.CV" Version="4.12.0.5764" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3595.46" />
    <PackageReference Include="MouseKeyHook" Version="5.7.1" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
  </ItemGroup>

</Project>